### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by regulad** [squirrelnetmc/AdvancementHunt#6]
# Messages
* Messages are handled very poorly and cause all sorts of issues.
1. The text "Creating World..." is hard-coded, not displayed to all players, and frankly just doesn't work.
1. Messages use both their own placeholders and PlaceholderAPI placeholders. All placeholders should be handled by PlaceholderAPI.
1. Add support for sending messages to the Subtitle
1. Advancements are displayed by their Namespaced ID, not their display name. Another Placeholder (`advancement_name`) must be added that displays the display name.
1. Add a priority system so 1 message ill always display over another one if 2 are sent to the same place at once.

**Comment by abhiram555** [comment]
fix in #18
